### ISSUE TITLE
Establish and Track Code Coverage

### ISSUE THREAD

**Issue by davidbegin** [AlanSwenson/amz-review-scraper#16]
So you have some tests now, and you want always make sure you are maintaining and hopefully increasing coverage. I would figure out a code coverage tool, and enforce it in travis and add a badge to readme.

**Comment by AlanSwenson** [comment]
like coveralls?

**Comment by AlanSwenson** [comment]
actually code climate looks kinda cool since it tracks code quality also

**Comment by AlanSwenson** [comment]
@davidbegin decided to go with coveralls. decision was based on the "big" companies that use it. Figure it maybe more helpful to learn this one that the other.  Also, it rules.  Now I know what tests Im missing.
