### ISSUE TITLE
Extract out a Chunk of HTML for testing.

### ISSUE THREAD

**Issue by davidbegin** [AlanSwenson/amz-review-scraper#17]
Right now with the Giant HTML file, it is hard to look through and understand what the code is looking for. And also makes the project look like it's HTML. It being real is a great advantage, But I would think of an easy way to a run a test against real html, without saving it. And the regular test should just use an artificially trimmed chunk

**Comment by AlanSwenson** [comment]
cutting this down is harder than it seems

**Comment by AlanSwenson** [comment]
not really feasible or efficient use of time for now
